In [211]:
import tensorflow as tf
import numpy as np
import pandas as pd

### Classification Task

In [212]:
mnist = tf.keras.datasets.mnist
(X_train , y_train), (X_test , y_test) = mnist.load_data()

In [213]:
X_train.shape

(60000, 28, 28)

In [214]:
y_train.shape

(60000,)

In [215]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [216]:
X_train = X_train / 255.0
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [217]:
X_test = X_test / 255.0

In [218]:
y_train

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [219]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout
model = Sequential([
    Input(shape=(28,28)),
    Flatten(),
    Dense(64, activation = 'relu'),
    Dropout(0.2),
    Dense(10)
])

In [220]:
nonsense_prediction = model(X_train[:1]).numpy()
nonsense_prediction

array([[ 0.28286707, -0.4599121 ,  0.89633703,  0.05771645, -0.4625449 ,
         0.17856602,  0.02672634,  0.39216137,  0.05124475, -0.02959628]],
      dtype=float32)

In [221]:
tf.nn.softmax(nonsense_prediction).numpy()

array([[0.11222187, 0.05339402, 0.20725459, 0.08959749, 0.05325363,
        0.10110676, 0.08686344, 0.12518245, 0.08901951, 0.08210628]],
      dtype=float32)

In [222]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
loss_fn = SparseCategoricalCrossentropy(from_logits=True)
# -tf.math.log(1/10)
loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.291578531265259>

In [223]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate = 0.01)
model.compile(optimizer = optimizer, loss = loss_fn, metrics = ['accuracy'])

In [224]:
model.fit(X_train, y_train, epochs = 10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8957 - loss: 0.3404
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 985us/step - accuracy: 0.9248 - loss: 0.2603
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 895us/step - accuracy: 0.9317 - loss: 0.2367
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 857us/step - accuracy: 0.9357 - loss: 0.2239
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 849us/step - accuracy: 0.9375 - loss: 0.2218
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 926us/step - accuracy: 0.9398 - loss: 0.2149
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 906us/step - accuracy: 0.9409 - loss: 0.2142
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 910us/step - accuracy: 0.9445 - loss: 0.2005
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 924us/step - accuracy: 0.9444 - loss: 0.2049
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 913us/step - accuracy: 0.9457 - loss: 0.2010


In [225]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.9562 - loss: 0.1992


[0.19919990003108978, 0.9562000036239624]